### ISSUE TITLE
Fatal node/puppeteer error when refreshing search index

### ISSUE THREAD

**Issue by jaycolmvar** [electricbookworks/electric-book#519]
I decided to try out function 8, "Refresh search index", in run-linux.sh. I have previously used option 3, "Run as a web site". It builds without error, and I am able to access the resulting web site at http://127.0.0.1:4000. However when I run the "refresh search index" function, taking the defaults, I get the following error:

Generating index ...
Indexing /home/jaycolmvar/src/rsbf-wip/_site/book/text/index.html
(node:17052) UnhandledPromiseRejectionWarning: Error: Protocol error (Page.navigate): Cannot navigate to invalid URL
    at Promise (/home/jaycolmvar/src/rsbf-wip/node_modules/puppeteer/lib/Connection.js:183:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/home/jaycolmvar/src/rsbf-wip/node_modules/puppeteer/lib/Connection.js:182:12)
    at navigate (/home/jaycolmvar/src/rsbf-wip/node_modules/puppeteer/lib/FrameManager.js:118:39)
    at FrameManager.navigateFrame (/home/jaycolmvar/src/rsbf-wip/node_modules/puppeteer/lib/FrameManager.js:95:7)
    at Frame.goto (/home/jaycolmvar/src/rsbf-wip/node_modules/puppeteer/lib/FrameManager.js:406:37)
    at Frame.<anonymous> (/home/jaycolmvar/src/rsbf-wip/node_modules/puppeteer/lib/helper.js:112:23)
    at Page.goto (/home/jaycolmvar/src/rsbf-wip/node_modules/puppeteer/lib/Page.js:672:49)
    at Page.<anonymous> (/home/jaycolmvar/src/rsbf-wip/node_modules/puppeteer/lib/helper.js:112:23)
    at /home/jaycolmvar/src/rsbf-wip/_site/assets/js/render-search-index.js:50:24
  -- ASYNC --
    at Frame.<anonymous> (/home/jaycolmvar/src/rsbf-wip/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.goto (/home/jaycolmvar/src/rsbf-wip/node_modules/puppeteer/lib/Page.js:672:49)
    at Page.<anonymous> (/home/jaycolmvar/src/rsbf-wip/node_modules/puppeteer/lib/helper.js:112:23)
    at /home/jaycolmvar/src/rsbf-wip/_site/assets/js/render-search-index.js:50:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:17052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17052) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I would be happy to try to put together a minimal reproducible test case, but before I do that I wanted to see if this was something that had been seen before and had an obvious solution.

P.S. I don't know if this is related, but I've had no success in getting my installed npm packages (as reflected in packages-lock.json, I presume) to match what appears to be installed as reflected in packages-lock.json in the EBT repository. I know very little about node.js and npm, and have just been fumbling about doing "npm update" to try to get the latest versions of packages.

**Comment by arthurattwell** [comment]
Thanks, @jaycolmvar. The 'Refresh search index' option relies on the `files` list for the web output (or app output, if you're doing the app search index) being accurate in `_data/meta.yml`. Puppeteer opens each file in headless Chrome and web-scrapes it to create an index. If a file in the `files` list isn't actually present in the site build, then it will fail. Some things come to mind:

1. Is it possible that your `files` list contains a file that isn't present or has been excluded in a config file?
2. We do need better error handling, so that if a file isn't present Puppeteer just skips it and moves on.
3. There may be a bug I haven't spotted yet. I'll do a quick test to try to replicate this myself.

As for the package-lock.json file: I think we should exclude that from the EBT, actually, as we did [recently for the Gemfile.lock](https://github.com/electricbookworks/electric-book/pull/509/commits/0fe75c4dac3a22ffc08b1400fb2570e7d19f4d7a). I don't think it's important for the template to force specific dependency versions like this. That lock file is probably only important when a team of people are working on a project where it's critical for every build to be absolutely identical. I may PR that change shortly (and will ask @LouiseSteward for her view, too). If you think otherwise, let me know?

**Comment by arthurattwell** [comment]
PS @jaycolmvar A possibility: it seems from the log that Puppeteer is failing when trying to open  `_site/book/text/index.html`, which might mean that there isn't a `book/text/index.md` file in your project.

**Comment by jaycolmvar** [comment]
Thanks very much for your suggestions. It's possible that the problem may be due to my misunderstandings about how the various index.md files should be configured and where all the files should go. Right now I have index.md files at three levels: the "root" level of the project, under the "book" subdirectory, and under the book/text subdirectory (where all my chapter files are located).

At the root level the index.md file looks as follows:

    ---
    title: XXXXXX
    style: home
    ---
    
    {% include metadata %}
    
    # XXXXXX
    {:.no_toc}
    
    This is the web version of *XXXXXX*.
    
    - [web version]({{ site.url }}/book/)

In the book subdirectory I have an index.md file that is identical to the index.md files included in the default electric-book/book or electric-book/samples directory:

    ---
    # This file redirects the user elsewhere.
    # By default, to the index page in the text folder.
    layout: min
    ---
    
    {% include redirect target="text" %}

And then in book/text I have a third index.md file that is identical to the corresponding index.md files in electric-book/book/text and electric-book/samples/text:

    ---
    style: cover
    ---
    
    {% include cover %}

When I generate the web version I do *not* specify a base URL, so the project page ends up at http://127.0.0.1:4000/ and the book cover ends up at http://127.0.0.1:4000/book/.

Also, as far as I can tell the lists of files in _data/meta.yml match up with the files that are actually there. This includes both the "files:" section under "web:" and the files listed under the "nav:" section under "web:".

I suspect what is going on here is that I just don't fully understand how the project/book directories are supposed to be structured and how the various URL-related configuration parameters work.

I can also try doing a test book that is an minimal as possible, and possibly even try to put some print statements in the puppeteer code to see what file it's failing on.
